export const typesVoie = [
  { key: "ALL", libelle: "Allée" },
  { key: "AV", libelle: "Avenue" },
  { key: "BAT", libelle: "Batiment" },
  { key: "BD", libelle: "Boulevard" },
  { key: "C", libelle: "Cours" },
  { key: "CAN", libelle: "Canal" },
  { key: "CAS", libelle: "CASERNE" },
  { key: "CAV", libelle: "CAVEE" },
  { key: "CEI", libelle: "CEINTURE" },
  { key: "CEL", libelle: "CELLIER" },
  { key: "CEN", libelle: "CENTRE" },
  { key: "CGE", libelle: "COLLEGE" },
  { key: "CH", libelle: "CHASSE" },
  { key: "CHA", libelle: "CHATEAU" },
  { key: "CHE", libelle: "Chemin" },
  { key: "CHN", libelle: "CHANTIER" },
  { key: "CHP", libelle: "CHAPELLE" },
  { key: "CHS", libelle: "Chaussée" },
  { key: "CHT", libelle: "CHEMINEMENT" },
  { key: "CHV", libelle: "CHEMIN VICINAL" },
  { key: "CI", libelle: "Cité" },
  { key: "CIM", libelle: "CIMETIERE" },
  { key: "CIN", libelle: "CINEMA" },
  { key: "CL", libelle: "Clos" },
  { key: "CLB", libelle: "CLUB" },
  { key: "CLI", libelle: "CLINIQUE" },
  { key: "CLL", libelle: "COL" },
  { key: "CLO", libelle: "CLOITRE" },
  { key: "CN", libelle: "COIN" },
  { key: "CO", libelle: "COUR" },
  { key: "COE", libelle: "COLLINE" },
  { key: "COG", libelle: "Cottage" },
  { key: "COL", libelle: "COLONIE" },
  { key: "COM", libelle: "COMMISSARIAT" },
  { key: "COR", libelle: "CORNICHE" },
  { key: "COT", libelle: "COTE" },
  { key: "COU", libelle: "COULOIR" },
  { key: "CRO", libelle: "CARROI" },
  { key: "CRX", libelle: "CROIX" },
  { key: "CTE", libelle: "CENTRAL TELEPHONIQUE" },
  { key: "CUR", libelle: "CURE" },
  { key: "DEG", libelle: "DEGRE" },
  { key: "DEP", libelle: "DEPOT" },
  { key: "DES", libelle: "DESCENTE" },
  { key: "DIG", libelle: "DIGUE" },
  { key: "DOM", libelle: "DOMAINE" },
  { key: "DON", libelle: "DIRECTION" },
  { key: "ECA", libelle: "ECART" },
  { key: "ECL", libelle: "ECLUSE" },
  { key: "ECO", libelle: "ECOLE" },
  { key: "ECV", libelle: "ENCLAVE" },
  { key: "EGL", libelle: "EGLISE" },
  { key: "EMP", libelle: "EMPLACEMENT" },
  { key: "EN", libelle: "ENCEINTE" },
  { key: "ENC", libelle: "ENCLOS" },
  { key: "ENT", libelle: "ENTREPOT" },
  { key: "ESC", libelle: "ESCALIER" },
  { key: "ESP", libelle: "ESPLANADE" },
  { key: "ETA", libelle: "ETABLISSEMENT" },
  { key: "ETG", libelle: "ETANG" },
  { key: "FAC", libelle: "FACADE" },
  { key: "FCU", libelle: "FACULTE" },
  { key: "FER", libelle: "FERME" },
  { key: "FG", libelle: "Faubourg" },
  { key: "FOL", libelle: "FOLIE" },
  { key: "FON", libelle: "FONTAINE" },
  { key: "FOR", libelle: "FORET" },
  { key: "FOS", libelle: "FOSSE" },
  { key: "FOY", libelle: "FOYER" },
  { key: "FRI", libelle: "FRICHE" },
  { key: "FT", libelle: "FORT" },
  { key: "GA", libelle: "GARE" },
  { key: "GAL", libelle: "GALERIE" },
  { key: "GDI", libelle: "GRAND IMPASSE" },
  { key: "GED", libelle: "GENDARMERIE" },
  { key: "GEN", libelle: "GRAND ENSEMBLE" },
  { key: "GGE", libelle: "GARAGE" },
  { key: "GLA", libelle: "GLACIS" },
  { key: "GPE", libelle: "GROUPE" },
  { key: "GR", libelle: "GRAND RUE" },
  { key: "GRI", libelle: "GRILLE" },
  { key: "GRN", libelle: "GARENNE" },
  { key: "GRP", libelle: "GROUPEMENT" },
  { key: "GSC", libelle: "GROUPE SCOLAIRE" },
  { key: "GUE", libelle: "GUE" },
  { key: "HA", libelle: "HALAGE" },
  { key: "HAL", libelle: "HALLE" },
  { key: "HAM", libelle: "Hameau" },
  { key: "HCE", libelle: "HOSPICE" },
  { key: "HIP", libelle: "HIPPODROME" },
  { key: "HLM", libelle: "H.L.M." },
  { key: "HOP", libelle: "HOPITAL" },
  { key: "HOT", libelle: "HOTEL" },
  { key: "HUT", libelle: "HUTTE" },
  { key: "ILE", libelle: "ILE" },
  { key: "ILO", libelle: "ILOT" },
  { key: "IMB", libelle: "Immeuble" },
  { key: "IMP", libelle: "Impasse" },
  { key: "INS", libelle: "INSTITUT" },
  { key: "ISP", libelle: "INSPECTION" },
  { key: "JAR", libelle: "JARDIN" },
  { key: "JET", libelle: "JETEE" },
  { key: "JUS", libelle: "JUSTICE" },
  { key: "LD", libelle: "LIEU DIT" },
  { key: "LEV", libelle: "LEVEE" },
  { key: "LOT", libelle: "Lotissement" },
  { key: "LYC", libelle: "LYCEE" },
  { key: "MA", libelle: "MARE" },
  { key: "MAG", libelle: "MAGASIN" },
  { key: "MAI", libelle: "Maison" },
  { key: "MAN", libelle: "MANOIR" },
  { key: "MAR", libelle: "MARCHE" },
  { key: "MAS", libelle: "MAS" },
  { key: "MAT", libelle: "MATERNITE" },
  { key: "MET", libelle: "METRO" },
  { key: "MF", libelle: "MAISON FORESTIERE" },
  { key: "MG", libelle: "MAISON DE GARDE" },
  { key: "ML", libelle: "MAIL" },
  { key: "MOU", libelle: "MOULIN" },
  { key: "MRI", libelle: "MAIRIE" },
  { key: "MTE", libelle: "Montée" },
  { key: "MUS", libelle: "MUSEE" },
  { key: "NTE", libelle: "NOUVELLE ROUTE" },
  { key: "OBS", libelle: "OBSERVATOIRE" },
  { key: "OCT", libelle: "OCTROI" },
  { key: "PA", libelle: "PARVIS" },
  { key: "PAE", libelle: "PETITE AVENUE" },
  { key: "PAL", libelle: "PALAIS" },
  { key: "PAR", libelle: "Parc" },
  { key: "PAS", libelle: "Passage" },
  { key: "PAT", libelle: "PATURE" },
  { key: "PAV", libelle: "Pavillon" },
  { key: "PBY", libelle: "PRESBYTERE" },
  { key: "PCE", libelle: "PORCHE" },
  { key: "PER", libelle: "PERYSTILE" },
  { key: "PHA", libelle: "PHARMACIE" },
  { key: "PIE", libelle: "PIECE" },
  { key: "PIM", libelle: "PETITE IMPASSE" },
  { key: "PKG", libelle: "PARKING" },
  { key: "PL", libelle: "Place" },
  { key: "PLA", libelle: "PLAINE" },
  { key: "PLC", libelle: "PLACIS" },
  { key: "PLE", libelle: "PASSERELLE" },
  { key: "PLT", libelle: "PLATEAU" },
  { key: "PLY", libelle: "PETIT LYCEE" },
  { key: "PO", libelle: "PONT" },
  { key: "POI", libelle: "POINTE" },
  { key: "POR", libelle: "Porte" },
  { key: "POT", libelle: "POTERNE" },
  { key: "POU", libelle: "POURTOUR" },
  { key: "PPA", libelle: "PETIT PASSAGE" },
  { key: "PR", libelle: "PETITE RUE" },
  { key: "PRA", libelle: "PRAIRIE" },
  { key: "PRE", libelle: "PRE" },
  { key: "PRO", libelle: "PROMENADE" },
  { key: "PRQ", libelle: "PRESQUILE" },
  { key: "PRT", libelle: "PETITE ROUTE" },
  { key: "PRU", libelle: "PREAU" },
  { key: "PT", libelle: "PORT" },
  { key: "PTE", libelle: "POSTE" },
  { key: "Q", libelle: "Quai" },
  { key: "QU", libelle: "Quartier" },
  { key: "R", libelle: "Rue" },
  { key: "RAC", libelle: "RACCOURCI" },
  { key: "RAM", libelle: "Rampe" },
  { key: "REM", libelle: "REMPART" },
  { key: "RES", libelle: "Résidence" },
  { key: "RNT", libelle: "RESTAURANT" },
  { key: "ROC", libelle: "ROCADE" },
  { key: "ROQ", libelle: "ROQUET" },
  { key: "ROT", libelle: "ROTONDE" },
  { key: "ROU", libelle: "ROULADE" },
  { key: "RP", libelle: "ROND POINT" },
  { key: "RTE", libelle: "Route" },
  { key: "RUL", libelle: "Ruelle" },
  { key: "SAN", libelle: "SANATORIUM" },
  { key: "SAP", libelle: "SAPUM" },
  { key: "SAS", libelle: "SAS" },
  { key: "SCE", libelle: "SERVICE" },
  { key: "SEC", libelle: "SECTION" },
  { key: "SEM", libelle: "SEMINAIRE" },
  { key: "SEN", libelle: "Sentier" },
  { key: "SNT", libelle: "SENTE" },
  { key: "SOC", libelle: "SOCIETE" },
  { key: "SQ", libelle: "Square" },
  { key: "STA", libelle: "STADE" },
  { key: "STN", libelle: "STAND" },
  { key: "STO", libelle: "STATION" },
  { key: "TE", libelle: "TERRASSE" },
  { key: "TEA", libelle: "TERRAIN" },
  { key: "TEN", libelle: "TENUE" },
  { key: "TER", libelle: "TERTRE" },
  { key: "THE", libelle: "THEATRE" },
  { key: "TOU", libelle: "TOUR" },
  { key: "TP", libelle: "TERRE PLEIN" },
  { key: "TRA", libelle: "TRAVERSE" },
  { key: "TRG", libelle: "TRIEGE" },
  { key: "TRI", libelle: "TRIAGE" },
  { key: "TUI", libelle: "TUILERIE" },
  { key: "USI", libelle: "USINE" },
  { key: "VAL", libelle: "VAL" },
  { key: "VCH", libelle: "VIEUX CHEMIN" },
  { key: "VEL", libelle: "VELODROME" },
  { key: "VEN", libelle: "VENELLE" },
  { key: "VGE", libelle: "VILLAGE" },
  { key: "VIA", libelle: "VIADUC" },
  { key: "VIL", libelle: "VILLE" },
  { key: "VLA", libelle: "VILLA" },
  { key: "VLE", libelle: "VALLEE" },
  { key: "VNO", libelle: "VILLE NOUVELLE" },
  { key: "VO", libelle: "Voie" },
  { key: "VON", libelle: "VALLON" },
  { key: "VOY", libelle: "VOYEUL" },
  { key: "ZAC", libelle: "ZAC" },
  { key: "ZI", libelle: "ZONE INDUSTRIELLE" },
  { key: "ZUP", libelle: "Z.U.P." },
];
